### ISSUE TITLE
Can not get this to work with Matomo-Version: 5.0.2

### ISSUE THREAD

**Issue by githuppi** [btourman/goal-conversion-export#3]
Hello,

I am struggling to get this working with Matomo-Version: 5.0.2. 

I can edit the plugin.json for the higher version but after the Installation (load from .zip or through FTP) there is no functionality within the Matomo Backend:

**Backend Link-Action:**
`…/matomo/index.php?module=GoalConversionExport&action=index&idSite=2&period=day&date=today`

**When Inspecting the Page for errors in Chrome I get:**

```
index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200 Uncaught TypeError: Object(...) is not a function
    at Module.fae3 (index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200:10444)
    at o (index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200:599)
    at 19dc (index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200:1441)
    at index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200:1455
    at index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200:381
    at index.php?module=Proxy&action=getUmdJs&chunk=2&cb=70a273c69b19428001e5dea4b838384c:200:430

```

Is there a workaround? Or is it still not supported for higher versions of Matomo?

Kind regards
Dennis
